# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Wed Nov 13 17:16:09 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1412, 812)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(99999, 99999))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 8, 861, 741))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_Queue = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_Queue.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Queue.setObjectName("verticalLayout_Queue")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_Queue.addWidget(self.label_10)
        self.tableWidget_PacketsQueue = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_PacketsQueue.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.tableWidget_PacketsQueue.setFont(font)
        self.tableWidget_PacketsQueue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_PacketsQueue.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget_PacketsQueue.setObjectName("tableWidget_PacketsQueue")
        self.tableWidget_PacketsQueue.setColumnCount(5)
        self.tableWidget_PacketsQueue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(4, item)
        self.verticalLayout_Queue.addWidget(self.tableWidget_PacketsQueue)
        self.horizontalLayout_BottomButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_BottomButtons.setObjectName("horizontalLayout_BottomButtons")
        self.pushButton_sendAll = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sendAll.setObjectName("pushButton_sendAll")
        self.horizontalLayout_BottomButtons.addWidget(self.pushButton_sendAll)
        self.pushButton_addPacket = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addPacket.sizePolicy().hasHeightForWidth())
        self.pushButton_addPacket.setSizePolicy(sizePolicy)
        self.pushButton_addPacket.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_addPacket.setObjectName("pushButton_addPacket")
        self.horizontalLayout_BottomButtons.addWidget(self.pushButton_addPacket)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_BottomButtons.addItem(spacerItem)
        self.verticalLayout_Queue.addLayout(self.horizontalLayout_BottomButtons)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(880, 8, 521, 741))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_Type_Fields = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_Type_Fields.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Type_Fields.setObjectName("verticalLayout_Type_Fields")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_Type_Fields.addWidget(self.label_11)
        self.tabWidget_setPacket = QtWidgets.QTabWidget(self.layoutWidget1)
        self.tabWidget_setPacket.setEnabled(False)
        self.tabWidget_setPacket.setObjectName("tabWidget_setPacket")
        self.tab_TCP = QtWidgets.QWidget()
        self.tab_TCP.setObjectName("tab_TCP")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_TCP)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 501, 671))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_FieldsTCP = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_FieldsTCP.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_FieldsTCP.setObjectName("gridLayout_FieldsTCP")
        self.lineEdit_paddingTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_paddingTCP.setObjectName("lineEdit_paddingTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_paddingTCP, 12, 1, 1, 1)
        self.checkBox_autoReservedTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_autoReservedTCP.setObjectName("checkBox_autoReservedTCP")
        self.gridLayout_FieldsTCP.addWidget(self.checkBox_autoReservedTCP, 6, 2, 1, 1)
        self.checkBox_autoChcksumTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_autoChcksumTCP.setObjectName("checkBox_autoChcksumTCP")
        self.gridLayout_FieldsTCP.addWidget(self.checkBox_autoChcksumTCP, 9, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_deletePacketTCP = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_deletePacketTCP.sizePolicy().hasHeightForWidth())
        self.pushButton_deletePacketTCP.setSizePolicy(sizePolicy)
        self.pushButton_deletePacketTCP.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_deletePacketTCP.setObjectName("pushButton_deletePacketTCP")
        self.horizontalLayout.addWidget(self.pushButton_deletePacketTCP)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_sendPacketTCP = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_sendPacketTCP.setObjectName("pushButton_sendPacketTCP")
        self.horizontalLayout.addWidget(self.pushButton_sendPacketTCP)
        self.pushButton_saveTCP = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_saveTCP.setObjectName("pushButton_saveTCP")
        self.horizontalLayout.addWidget(self.pushButton_saveTCP)
        self.gridLayout_FieldsTCP.addLayout(self.horizontalLayout, 14, 0, 1, 3)
        self.lineEdit_seqTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_seqTCP.setObjectName("lineEdit_seqTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_seqTCP, 3, 1, 1, 1)
        self.lineEdit_reservedTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_reservedTCP.setObjectName("lineEdit_reservedTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_reservedTCP, 6, 1, 1, 1)
        self.textEdit_dataTCP = QtWidgets.QTextEdit(self.layoutWidget2)
        self.textEdit_dataTCP.setObjectName("textEdit_dataTCP")
        self.gridLayout_FieldsTCP.addWidget(self.textEdit_dataTCP, 13, 1, 1, 1)
        self.lineEdit_windowSizeTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_windowSizeTCP.setObjectName("lineEdit_windowSizeTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_windowSizeTCP, 8, 1, 1, 1)
        self.lineEdit_urgentPointerTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_urgentPointerTCP.setObjectName("lineEdit_urgentPointerTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_urgentPointerTCP, 10, 1, 1, 1)
        self.lineEdit_srcPortTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_srcPortTCP.setObjectName("lineEdit_srcPortTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_srcPortTCP, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_FieldsTCP.addLayout(self.horizontalLayout_2, 15, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.gridLayout_FieldsTCP.addWidget(self.label, 1, 0, 1, 1)
        self.checkBox_autoDataOffsetTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_autoDataOffsetTCP.sizePolicy().hasHeightForWidth())
        self.checkBox_autoDataOffsetTCP.setSizePolicy(sizePolicy)
        self.checkBox_autoDataOffsetTCP.setObjectName("checkBox_autoDataOffsetTCP")
        self.gridLayout_FieldsTCP.addWidget(self.checkBox_autoDataOffsetTCP, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_FieldsTCP.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_FieldsTCP.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_chksumTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_chksumTCP.setObjectName("lineEdit_chksumTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_chksumTCP, 9, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_FieldsTCP.addWidget(self.label_15, 12, 0, 1, 1)
        self.lineEdit_dataOffsetTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_dataOffsetTCP.setObjectName("lineEdit_dataOffsetTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_dataOffsetTCP, 5, 1, 1, 1)
        self.gridLayout_Flags = QtWidgets.QGridLayout()
        self.gridLayout_Flags.setObjectName("gridLayout_Flags")
        self.checkBox_finTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_finTCP.setObjectName("checkBox_finTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_finTCP, 3, 1, 1, 1)
        self.checkBox_pshTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_pshTCP.setObjectName("checkBox_pshTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_pshTCP, 3, 0, 1, 1)
        self.checkBox_urgTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_urgTCP.setObjectName("checkBox_urgTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_urgTCP, 0, 0, 1, 1)
        self.checkBox_ackTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_ackTCP.setObjectName("checkBox_ackTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_ackTCP, 1, 0, 1, 1)
        self.checkBox_rstTSP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_rstTSP.setObjectName("checkBox_rstTSP")
        self.gridLayout_Flags.addWidget(self.checkBox_rstTSP, 0, 1, 1, 1)
        self.checkBox_synTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_synTCP.setObjectName("checkBox_synTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_synTCP, 1, 1, 1, 1)
        self.gridLayout_FieldsTCP.addLayout(self.gridLayout_Flags, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_FieldsTCP.addWidget(self.label_9, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_FieldsTCP.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_dstPortTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_dstPortTCP.setObjectName("lineEdit_dstPortTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_dstPortTCP, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.gridLayout_FieldsTCP.addWidget(self.label_13, 11, 0, 1, 1)
        self.checkBox_autoPaddingTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_autoPaddingTCP.setObjectName("checkBox_autoPaddingTCP")
        self.gridLayout_FieldsTCP.addWidget(self.checkBox_autoPaddingTCP, 12, 2, 1, 1)
        self.textEdit_optionsTCP = QtWidgets.QTextEdit(self.layoutWidget2)
        self.textEdit_optionsTCP.setObjectName("textEdit_optionsTCP")
        self.gridLayout_FieldsTCP.addWidget(self.textEdit_optionsTCP, 11, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_14.setObjectName("label_14")
        self.gridLayout_FieldsTCP.addWidget(self.label_14, 13, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_FieldsTCP.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_FieldsTCP.addWidget(self.label_7, 7, 0, 1, 1)
        self.lineEdit_ackTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_ackTCP.setObjectName("lineEdit_ackTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_ackTCP, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_FieldsTCP.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_FieldsTCP.addWidget(self.label_12, 10, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_FieldsTCP.addWidget(self.label_8, 8, 0, 1, 1)
        self.tabWidget_setPacket.addTab(self.tab_TCP, "")
        self.tab_UDP = QtWidgets.QWidget()
        self.tab_UDP.setObjectName("tab_UDP")
        self.tabWidget_setPacket.addTab(self.tab_UDP, "")
        self.tab_ICMP = QtWidgets.QWidget()
        self.tab_ICMP.setObjectName("tab_ICMP")
        self.tabWidget_setPacket.addTab(self.tab_ICMP, "")
        self.tab_IP = QtWidgets.QWidget()
        self.tab_IP.setObjectName("tab_IP")
        self.tabWidget_setPacket.addTab(self.tab_IP, "")
        self.verticalLayout_Type_Fields.addWidget(self.tabWidget_setPacket)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1412, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSetInterface = QtWidgets.QAction(MainWindow)
        self.actionSetInterface.setObjectName("actionSetInterface")
        self.menu.addAction(self.actionSetInterface)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_setPacket.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Генератор пакетов", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Очередь пакетов", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Тип пакета", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Адрес отправителя", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Адрес получателя", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Порт отправителя", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Порт получателя", None, -1))
        self.pushButton_sendAll.setText(QtWidgets.QApplication.translate("MainWindow", "Отправить все пакеты", None, -1))
        self.pushButton_addPacket.setText(QtWidgets.QApplication.translate("MainWindow", "Создать пакет", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Настройка пакета", None, -1))
        self.checkBox_autoReservedTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.checkBox_autoChcksumTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.pushButton_deletePacketTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Удалить пакет", None, -1))
        self.pushButton_sendPacketTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Отправить пакет", None, -1))
        self.pushButton_saveTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить пакет", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Порт отправителя", None, -1))
        self.checkBox_autoDataOffsetTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Зарезервированное поле", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Порт получателя", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Заполнение", None, -1))
        self.checkBox_finTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[5] FIN", None, -1))
        self.checkBox_pshTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[2] PSH", None, -1))
        self.checkBox_urgTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[0] URG", None, -1))
        self.checkBox_ackTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[1] ACK", None, -1))
        self.checkBox_rstTSP.setText(QtWidgets.QApplication.translate("MainWindow", "[3] RST", None, -1))
        self.checkBox_synTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[4] SYN", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Контрольная сумма", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Смещение данных", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Опции", None, -1))
        self.checkBox_autoPaddingTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Данные", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "ACK", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Флаги", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "SEQ", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Указатель на срочные данные", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Размер окна", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab_TCP), QtWidgets.QApplication.translate("MainWindow", "TCP", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab_UDP), QtWidgets.QApplication.translate("MainWindow", "UDP", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab_ICMP), QtWidgets.QApplication.translate("MainWindow", "ICMP", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab_IP), QtWidgets.QApplication.translate("MainWindow", "IP", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Инструменты", None, -1))
        self.actionSetInterface.setText(QtWidgets.QApplication.translate("MainWindow", "Настройка интерфейсов...", None, -1))

