# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Sun Nov 24 03:55:19 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1478, 940)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(99999, 99999))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 8, 801, 871))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_Queue = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_Queue.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Queue.setObjectName("verticalLayout_Queue")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_Queue.addWidget(self.label_10)
        self.tableWidget_PacketsQueue = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_PacketsQueue.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        self.tableWidget_PacketsQueue.setFont(font)
        self.tableWidget_PacketsQueue.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_PacketsQueue.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_PacketsQueue.setTabKeyNavigation(False)
        self.tableWidget_PacketsQueue.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_PacketsQueue.setObjectName("tableWidget_PacketsQueue")
        self.tableWidget_PacketsQueue.setColumnCount(6)
        self.tableWidget_PacketsQueue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_PacketsQueue.setHorizontalHeaderItem(5, item)
        self.tableWidget_PacketsQueue.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_Queue.addWidget(self.tableWidget_PacketsQueue)
        self.horizontalLayout_BottomButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_BottomButtons.setObjectName("horizontalLayout_BottomButtons")
        self.pushButton_sendAll = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_sendAll.setObjectName("pushButton_sendAll")
        self.horizontalLayout_BottomButtons.addWidget(self.pushButton_sendAll)
        self.pushButton_addPacket = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addPacket.sizePolicy().hasHeightForWidth())
        self.pushButton_addPacket.setSizePolicy(sizePolicy)
        self.pushButton_addPacket.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_addPacket.setObjectName("pushButton_addPacket")
        self.horizontalLayout_BottomButtons.addWidget(self.pushButton_addPacket)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_BottomButtons.addItem(spacerItem)
        self.radioButton_ifDeleteAll = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_ifDeleteAll.setObjectName("radioButton_ifDeleteAll")
        self.horizontalLayout_BottomButtons.addWidget(self.radioButton_ifDeleteAll)
        self.verticalLayout_Queue.addLayout(self.horizontalLayout_BottomButtons)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(820, 8, 651, 881))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_Type_Fields = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_Type_Fields.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Type_Fields.setObjectName("verticalLayout_Type_Fields")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_Type_Fields.addWidget(self.label_11)
        self.tabWidget_setPacket = QtWidgets.QTabWidget(self.layoutWidget1)
        self.tabWidget_setPacket.setEnabled(False)
        self.tabWidget_setPacket.setObjectName("tabWidget_setPacket")
        self.tab_TCP = QtWidgets.QWidget()
        self.tab_TCP.setObjectName("tab_TCP")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_TCP)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 631, 811))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_FieldsTCP = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_FieldsTCP.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_FieldsTCP.setObjectName("gridLayout_FieldsTCP")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.gridLayout_FieldsTCP.addLayout(self.verticalLayout_2, 10, 0, 1, 1)
        self.lineEdit_windowSizeTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_windowSizeTCP.setObjectName("lineEdit_windowSizeTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_windowSizeTCP, 8, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_FieldsTCP.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_FieldsTCP.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_FieldsTCP.addWidget(self.label_19, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_FieldsTCP.addWidget(self.label_8, 8, 0, 1, 1)
        self.lineEdit_dataOffsetTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_dataOffsetTCP.setObjectName("lineEdit_dataOffsetTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_dataOffsetTCP, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_FieldsTCP.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_FieldsTCP.addWidget(self.label_17, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_FieldsTCP.addWidget(self.label_16, 1, 1, 1, 1)
        self.checkBox_autoDataOffsetTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_autoDataOffsetTCP.sizePolicy().hasHeightForWidth())
        self.checkBox_autoDataOffsetTCP.setSizePolicy(sizePolicy)
        self.checkBox_autoDataOffsetTCP.setObjectName("checkBox_autoDataOffsetTCP")
        self.gridLayout_FieldsTCP.addWidget(self.checkBox_autoDataOffsetTCP, 5, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_14.setObjectName("label_14")
        self.gridLayout_FieldsTCP.addWidget(self.label_14, 12, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.gridLayout_FieldsTCP.addWidget(self.label_24, 10, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_FieldsTCP.addWidget(self.label_21, 6, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_saveTCP = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_saveTCP.setObjectName("pushButton_saveTCP")
        self.horizontalLayout.addWidget(self.pushButton_saveTCP)
        self.gridLayout_FieldsTCP.addLayout(self.horizontalLayout, 13, 0, 1, 4)
        self.lineEdit_srcPortTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_srcPortTCP.setObjectName("lineEdit_srcPortTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_srcPortTCP, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.gridLayout_FieldsTCP.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit_reservedTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_reservedTCP.setObjectName("lineEdit_reservedTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_reservedTCP, 6, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_optionsTCP = QtWidgets.QTableWidget(self.layoutWidget2)
        self.tableWidget_optionsTCP.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget_optionsTCP.setObjectName("tableWidget_optionsTCP")
        self.tableWidget_optionsTCP.setColumnCount(3)
        self.tableWidget_optionsTCP.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_optionsTCP.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_optionsTCP.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_optionsTCP.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.tableWidget_optionsTCP, 0, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.pushButton_deleteOptionTCP = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_deleteOptionTCP.setObjectName("pushButton_deleteOptionTCP")
        self.gridLayout_2.addWidget(self.pushButton_deleteOptionTCP, 1, 2, 1, 1)
        self.pushButton_addOptionTCP = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_addOptionTCP.setObjectName("pushButton_addOptionTCP")
        self.gridLayout_2.addWidget(self.pushButton_addOptionTCP, 1, 1, 1, 1)
        self.gridLayout_FieldsTCP.addLayout(self.gridLayout_2, 11, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_FieldsTCP.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_FieldsTCP.addWidget(self.label_23, 9, 1, 1, 1)
        self.plainTextEdit_dataTCP = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        self.plainTextEdit_dataTCP.setObjectName("plainTextEdit_dataTCP")
        self.gridLayout_FieldsTCP.addWidget(self.plainTextEdit_dataTCP, 12, 2, 1, 1)
        self.lineEdit_checksumTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_checksumTCP.setObjectName("lineEdit_checksumTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_checksumTCP, 9, 2, 1, 1)
        self.lineEdit_dstPortTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_dstPortTCP.setObjectName("lineEdit_dstPortTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_dstPortTCP, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_FieldsTCP.addWidget(self.label_22, 8, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_FieldsTCP.addWidget(self.label_20, 5, 1, 1, 1)
        self.lineEdit_seqTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_seqTCP.setObjectName("lineEdit_seqTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_seqTCP, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_FieldsTCP.addWidget(self.label_2, 2, 0, 1, 1)
        self.checkBox_autoReservedTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_autoReservedTCP.setObjectName("checkBox_autoReservedTCP")
        self.gridLayout_FieldsTCP.addWidget(self.checkBox_autoReservedTCP, 6, 3, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_urgentPointerTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_urgentPointerTCP.setObjectName("lineEdit_urgentPointerTCP")
        self.verticalLayout_3.addWidget(self.lineEdit_urgentPointerTCP)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout_FieldsTCP.addLayout(self.verticalLayout_3, 10, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setObjectName("label_13")
        self.gridLayout_FieldsTCP.addWidget(self.label_13, 11, 0, 1, 1)
        self.checkBox_autoChecksumTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_autoChecksumTCP.setObjectName("checkBox_autoChecksumTCP")
        self.gridLayout_FieldsTCP.addWidget(self.checkBox_autoChecksumTCP, 9, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_FieldsTCP.addWidget(self.label_9, 9, 0, 1, 1)
        self.lineEdit_ackTCP = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_ackTCP.setObjectName("lineEdit_ackTCP")
        self.gridLayout_FieldsTCP.addWidget(self.lineEdit_ackTCP, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_FieldsTCP.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_FieldsTCP.addWidget(self.label_18, 3, 1, 1, 1)
        self.gridLayout_Flags = QtWidgets.QGridLayout()
        self.gridLayout_Flags.setObjectName("gridLayout_Flags")
        self.checkBox_finTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_finTCP.setObjectName("checkBox_finTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_finTCP, 3, 1, 1, 1)
        self.checkBox_pshTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_pshTCP.setObjectName("checkBox_pshTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_pshTCP, 3, 0, 1, 1)
        self.checkBox_urgTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_urgTCP.setObjectName("checkBox_urgTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_urgTCP, 0, 0, 1, 1)
        self.checkBox_ackTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_ackTCP.setObjectName("checkBox_ackTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_ackTCP, 1, 0, 1, 1)
        self.checkBox_rstTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_rstTCP.setObjectName("checkBox_rstTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_rstTCP, 0, 1, 1, 1)
        self.checkBox_synTCP = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox_synTCP.setObjectName("checkBox_synTCP")
        self.gridLayout_Flags.addWidget(self.checkBox_synTCP, 1, 1, 1, 1)
        self.gridLayout_FieldsTCP.addLayout(self.gridLayout_Flags, 7, 2, 1, 1)
        self.tabWidget_setPacket.addTab(self.tab_TCP, "")
        self.tab_UDP = QtWidgets.QWidget()
        self.tab_UDP.setObjectName("tab_UDP")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_UDP)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 631, 811))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_FieldsUDP = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_FieldsUDP.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_FieldsUDP.setObjectName("gridLayout_FieldsUDP")
        self.lineEdit_srcPortUDP = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_srcPortUDP.setObjectName("lineEdit_srcPortUDP")
        self.gridLayout_FieldsUDP.addWidget(self.lineEdit_srcPortUDP, 1, 2, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_86.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_86.setObjectName("label_86")
        self.gridLayout_FieldsUDP.addWidget(self.label_86, 5, 0, 1, 1)
        self.checkBox_autoLengthUDP = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkBox_autoLengthUDP.setObjectName("checkBox_autoLengthUDP")
        self.gridLayout_FieldsUDP.addWidget(self.checkBox_autoLengthUDP, 3, 3, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_87.setObjectName("label_87")
        self.gridLayout_FieldsUDP.addWidget(self.label_87, 1, 0, 1, 1)
        self.plainTextEdit_dataUDP = QtWidgets.QPlainTextEdit(self.layoutWidget_3)
        self.plainTextEdit_dataUDP.setObjectName("plainTextEdit_dataUDP")
        self.gridLayout_FieldsUDP.addWidget(self.plainTextEdit_dataUDP, 5, 2, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_91.setObjectName("label_91")
        self.gridLayout_FieldsUDP.addWidget(self.label_91, 2, 0, 1, 1)
        self.checkBox_autoChecksumUDP = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkBox_autoChecksumUDP.setObjectName("checkBox_autoChecksumUDP")
        self.gridLayout_FieldsUDP.addWidget(self.checkBox_autoChecksumUDP, 4, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_56.setObjectName("label_56")
        self.gridLayout_FieldsUDP.addWidget(self.label_56, 3, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_58.setObjectName("label_58")
        self.gridLayout_FieldsUDP.addWidget(self.label_58, 4, 1, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_96.setObjectName("label_96")
        self.gridLayout_FieldsUDP.addWidget(self.label_96, 1, 1, 1, 1)
        self.label_97 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_97.setObjectName("label_97")
        self.gridLayout_FieldsUDP.addWidget(self.label_97, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_FieldsUDP.addItem(spacerItem4, 7, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_FieldsUDP.addItem(spacerItem5, 6, 0, 1, 1)
        self.lineEdit_checksumUDP = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_checksumUDP.setObjectName("lineEdit_checksumUDP")
        self.gridLayout_FieldsUDP.addWidget(self.lineEdit_checksumUDP, 4, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.pushButton_saveUDP = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_saveUDP.setObjectName("pushButton_saveUDP")
        self.horizontalLayout_9.addWidget(self.pushButton_saveUDP)
        self.gridLayout_FieldsUDP.addLayout(self.horizontalLayout_9, 8, 0, 1, 4)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_57.setObjectName("label_57")
        self.gridLayout_FieldsUDP.addWidget(self.label_57, 4, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_55.setObjectName("label_55")
        self.gridLayout_FieldsUDP.addWidget(self.label_55, 3, 0, 1, 1)
        self.lineEdit_lengthUDP = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_lengthUDP.setObjectName("lineEdit_lengthUDP")
        self.gridLayout_FieldsUDP.addWidget(self.lineEdit_lengthUDP, 3, 2, 1, 1)
        self.lineEdit_dstPortUDP = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_dstPortUDP.setObjectName("lineEdit_dstPortUDP")
        self.gridLayout_FieldsUDP.addWidget(self.lineEdit_dstPortUDP, 2, 2, 1, 1)
        self.tabWidget_setPacket.addTab(self.tab_UDP, "")
        self.tab_ICMP = QtWidgets.QWidget()
        self.tab_ICMP.setObjectName("tab_ICMP")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_ICMP)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 631, 811))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_FieldsICMP = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_FieldsICMP.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_FieldsICMP.setObjectName("gridLayout_FieldsICMP")
        self.lineEdit_typeICMP = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_typeICMP.setObjectName("lineEdit_typeICMP")
        self.gridLayout_FieldsICMP.addWidget(self.lineEdit_typeICMP, 1, 2, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_67.setObjectName("label_67")
        self.gridLayout_FieldsICMP.addWidget(self.label_67, 2, 0, 1, 1)
        self.lineEdit_checksumICMP = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_checksumICMP.setObjectName("lineEdit_checksumICMP")
        self.gridLayout_FieldsICMP.addWidget(self.lineEdit_checksumICMP, 3, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.pushButton_saveICMP = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_saveICMP.setObjectName("pushButton_saveICMP")
        self.horizontalLayout_7.addWidget(self.pushButton_saveICMP)
        self.gridLayout_FieldsICMP.addLayout(self.horizontalLayout_7, 10, 0, 1, 4)
        self.plainTextEdit_dataICMP = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        self.plainTextEdit_dataICMP.setObjectName("plainTextEdit_dataICMP")
        self.gridLayout_FieldsICMP.addWidget(self.plainTextEdit_dataICMP, 7, 2, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_76.setObjectName("label_76")
        self.gridLayout_FieldsICMP.addWidget(self.label_76, 6, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_60.setObjectName("label_60")
        self.gridLayout_FieldsICMP.addWidget(self.label_60, 3, 0, 1, 1)
        self.lineEdit_codeICMP = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_codeICMP.setObjectName("lineEdit_codeICMP")
        self.gridLayout_FieldsICMP.addWidget(self.lineEdit_codeICMP, 2, 2, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_62.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_62.setObjectName("label_62")
        self.gridLayout_FieldsICMP.addWidget(self.label_62, 7, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_63.setObjectName("label_63")
        self.gridLayout_FieldsICMP.addWidget(self.label_63, 1, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_72.setObjectName("label_72")
        self.gridLayout_FieldsICMP.addWidget(self.label_72, 1, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_75.setObjectName("label_75")
        self.gridLayout_FieldsICMP.addWidget(self.label_75, 5, 1, 1, 1)
        self.lineEdit_identifierICMP = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_identifierICMP.setObjectName("lineEdit_identifierICMP")
        self.gridLayout_FieldsICMP.addWidget(self.lineEdit_identifierICMP, 5, 2, 1, 1)
        self.checkBox_autoChecksumICMP = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_autoChecksumICMP.setObjectName("checkBox_autoChecksumICMP")
        self.gridLayout_FieldsICMP.addWidget(self.checkBox_autoChecksumICMP, 3, 3, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_65.setObjectName("label_65")
        self.gridLayout_FieldsICMP.addWidget(self.label_65, 5, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_12.addWidget(self.label_52)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.gridLayout_FieldsICMP.addLayout(self.horizontalLayout_12, 0, 0, 1, 4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_13.addWidget(self.label_53)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.gridLayout_FieldsICMP.addLayout(self.horizontalLayout_13, 4, 0, 1, 4)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_61.setObjectName("label_61")
        self.gridLayout_FieldsICMP.addWidget(self.label_61, 6, 0, 1, 1)
        self.lineEdit_seqICMP = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_seqICMP.setObjectName("lineEdit_seqICMP")
        self.gridLayout_FieldsICMP.addWidget(self.lineEdit_seqICMP, 6, 2, 1, 1)
        self.comboBox_typeICMP = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_typeICMP.setObjectName("comboBox_typeICMP")
        self.comboBox_typeICMP.addItem("")
        self.comboBox_typeICMP.addItem("")
        self.comboBox_typeICMP.addItem("")
        self.gridLayout_FieldsICMP.addWidget(self.comboBox_typeICMP, 1, 3, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_FieldsICMP.addItem(spacerItem12, 8, 0, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_74.setObjectName("label_74")
        self.gridLayout_FieldsICMP.addWidget(self.label_74, 3, 1, 1, 1)
        self.checkBox_autoCodeICMP = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkBox_autoCodeICMP.setObjectName("checkBox_autoCodeICMP")
        self.gridLayout_FieldsICMP.addWidget(self.checkBox_autoCodeICMP, 2, 3, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_73.setObjectName("label_73")
        self.gridLayout_FieldsICMP.addWidget(self.label_73, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_FieldsICMP.addItem(spacerItem13, 9, 0, 1, 1)
        self.tabWidget_setPacket.addTab(self.tab_ICMP, "")
        self.tab_IP = QtWidgets.QWidget()
        self.tab_IP.setObjectName("tab_IP")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_IP)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 631, 811))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_FieldsIP = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_FieldsIP.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_FieldsIP.setObjectName("gridLayout_FieldsIP")
        self.comboBox_protocolIP = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_protocolIP.setObjectName("comboBox_protocolIP")
        self.comboBox_protocolIP.addItem("")
        self.comboBox_protocolIP.addItem("")
        self.comboBox_protocolIP.addItem("")
        self.comboBox_protocolIP.addItem("")
        self.gridLayout_FieldsIP.addWidget(self.comboBox_protocolIP, 11, 3, 1, 1)
        self.gridLayout_Flags_2 = QtWidgets.QGridLayout()
        self.gridLayout_Flags_2.setObjectName("gridLayout_Flags_2")
        self.checkBox_reservedFlagIP = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_reservedFlagIP.setObjectName("checkBox_reservedFlagIP")
        self.gridLayout_Flags_2.addWidget(self.checkBox_reservedFlagIP, 0, 0, 1, 1)
        self.checkBox_dontFragmentFlagIP = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_dontFragmentFlagIP.setObjectName("checkBox_dontFragmentFlagIP")
        self.gridLayout_Flags_2.addWidget(self.checkBox_dontFragmentFlagIP, 1, 0, 1, 1)
        self.checkBox_moreFragmentsFlagIP = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_moreFragmentsFlagIP.setObjectName("checkBox_moreFragmentsFlagIP")
        self.gridLayout_Flags_2.addWidget(self.checkBox_moreFragmentsFlagIP, 3, 0, 1, 1)
        self.gridLayout_FieldsIP.addLayout(self.gridLayout_Flags_2, 8, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_FieldsIP.addWidget(self.label_41, 6, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_FieldsIP.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_FieldsIP.addWidget(self.label_33, 4, 0, 1, 1)
        self.lineEdit_fragmentOffsetIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_fragmentOffsetIP.setObjectName("lineEdit_fragmentOffsetIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_fragmentOffsetIP, 9, 2, 1, 1)
        self.lineEdit_srcAddrIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_srcAddrIP.setObjectName("lineEdit_srcAddrIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_srcAddrIP, 1, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_FieldsIP.addWidget(self.label_38, 10, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_FieldsIP.addWidget(self.label_28, 3, 0, 1, 1)
        self.lineEdit_checksumIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_checksumIP.setObjectName("lineEdit_checksumIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_checksumIP, 12, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_FieldsIP.addWidget(self.label_47, 10, 1, 1, 1)
        self.lineEdit_protocolIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_protocolIP.setObjectName("lineEdit_protocolIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_protocolIP, 11, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_59.setObjectName("label_59")
        self.gridLayout_FieldsIP.addWidget(self.label_59, 3, 1, 1, 1)
        self.lineEdit_versionIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_versionIP.setObjectName("lineEdit_versionIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_versionIP, 3, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_FieldsIP.addWidget(self.label_46, 9, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_FieldsIP.addWidget(self.label_44, 12, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_FieldsIP.addWidget(self.label_35, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_autoIDataP = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_autoIDataP.setObjectName("checkBox_autoIDataP")
        self.verticalLayout.addWidget(self.checkBox_autoIDataP)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.gridLayout_FieldsIP.addLayout(self.verticalLayout, 14, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_FieldsIP.addWidget(self.label_29, 5, 0, 1, 1)
        self.lineEdit_identificationIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_identificationIP.setObjectName("lineEdit_identificationIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_identificationIP, 7, 2, 1, 1)
        self.checkBox_autoTotalLengthIP = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_autoTotalLengthIP.setObjectName("checkBox_autoTotalLengthIP")
        self.gridLayout_FieldsIP.addWidget(self.checkBox_autoTotalLengthIP, 6, 3, 1, 1)
        self.lineEdit_totalLengthIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_totalLengthIP.setObjectName("lineEdit_totalLengthIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_totalLengthIP, 6, 2, 1, 1)
        self.lineEdit_timeToLiveIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_timeToLiveIP.setObjectName("lineEdit_timeToLiveIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_timeToLiveIP, 10, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.pushButton_saveIP = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_saveIP.setObjectName("pushButton_saveIP")
        self.horizontalLayout_4.addWidget(self.pushButton_saveIP)
        self.gridLayout_FieldsIP.addLayout(self.horizontalLayout_4, 15, 0, 1, 4)
        self.lineEdit_IHL = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_IHL.setObjectName("lineEdit_IHL")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_IHL, 4, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_FieldsIP.addWidget(self.label_45, 7, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_FieldsIP.addWidget(self.label_34, 7, 0, 1, 1)
        self.checkBox_autoChecksumIP = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_autoChecksumIP.setObjectName("checkBox_autoChecksumIP")
        self.gridLayout_FieldsIP.addWidget(self.checkBox_autoChecksumIP, 12, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_FieldsIP.addWidget(self.label_42, 6, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_30.setObjectName("label_30")
        self.gridLayout_FieldsIP.addWidget(self.label_30, 14, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_FieldsIP.addWidget(self.label_36, 11, 0, 1, 1)
        self.comboBox_versionIP = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_versionIP.setObjectName("comboBox_versionIP")
        self.comboBox_versionIP.addItem("")
        self.comboBox_versionIP.addItem("")
        self.gridLayout_FieldsIP.addWidget(self.comboBox_versionIP, 3, 3, 1, 1)
        self.checkBox_autoOffsetIP = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_autoOffsetIP.setObjectName("checkBox_autoOffsetIP")
        self.gridLayout_FieldsIP.addWidget(self.checkBox_autoOffsetIP, 9, 3, 1, 1)
        self.checkBox_autoIHL = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_autoIHL.setObjectName("checkBox_autoIHL")
        self.gridLayout_FieldsIP.addWidget(self.checkBox_autoIHL, 4, 3, 1, 1)
        self.lineEdit_dstAddrIP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_dstAddrIP.setObjectName("lineEdit_dstAddrIP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_dstAddrIP, 2, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_FieldsIP.addWidget(self.label_27, 8, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_39.setObjectName("label_39")
        self.gridLayout_FieldsIP.addWidget(self.label_39, 13, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_FieldsIP.addWidget(self.label_48, 11, 1, 1, 1)
        self.lineEdit_DSCP = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_DSCP.setObjectName("lineEdit_DSCP")
        self.gridLayout_FieldsIP.addWidget(self.lineEdit_DSCP, 5, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_FieldsIP.addWidget(self.label_40, 5, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_FieldsIP.addWidget(self.label_43, 4, 1, 1, 1)
        self.plainTextEdit_dataIP = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_dataIP.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_dataIP.setSizePolicy(sizePolicy)
        self.plainTextEdit_dataIP.setObjectName("plainTextEdit_dataIP")
        self.gridLayout_FieldsIP.addWidget(self.plainTextEdit_dataIP, 14, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_FieldsIP.addWidget(self.label_51, 12, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_FieldsIP.addWidget(self.label_37, 9, 0, 1, 1)
        self.plainTextEdit_optionsIP = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
        self.plainTextEdit_optionsIP.setObjectName("plainTextEdit_optionsIP")
        self.gridLayout_FieldsIP.addWidget(self.plainTextEdit_optionsIP, 13, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.gridLayout_FieldsIP.addLayout(self.verticalLayout_4, 13, 1, 1, 1)
        self.tabWidget_setPacket.addTab(self.tab_IP, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 10, 631, 811))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_FieldsICMP_2 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_FieldsICMP_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_FieldsICMP_2.setObjectName("gridLayout_FieldsICMP_2")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_FieldsICMP_2.addItem(spacerItem17, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.pushButton_saveEthernet = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_saveEthernet.setObjectName("pushButton_saveEthernet")
        self.horizontalLayout_10.addWidget(self.pushButton_saveEthernet)
        self.gridLayout_FieldsICMP_2.addLayout(self.horizontalLayout_10, 3, 0, 1, 4)
        self.label_81 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_81.setObjectName("label_81")
        self.gridLayout_FieldsICMP_2.addWidget(self.label_81, 1, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_68.setObjectName("label_68")
        self.gridLayout_FieldsICMP_2.addWidget(self.label_68, 1, 0, 1, 1)
        self.comboBox_etherType = QtWidgets.QComboBox(self.layoutWidget_5)
        self.comboBox_etherType.setObjectName("comboBox_etherType")
        self.comboBox_etherType.addItem("")
        self.comboBox_etherType.addItem("")
        self.gridLayout_FieldsICMP_2.addWidget(self.comboBox_etherType, 1, 3, 1, 1)
        self.lineEdit_etherType = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_etherType.setObjectName("lineEdit_etherType")
        self.gridLayout_FieldsICMP_2.addWidget(self.lineEdit_etherType, 1, 2, 1, 1)
        self.tabWidget_setPacket.addTab(self.tab, "")
        self.verticalLayout_Type_Fields.addWidget(self.tabWidget_setPacket)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1478, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSetInterface = QtWidgets.QAction(MainWindow)
        self.actionSetInterface.setObjectName("actionSetInterface")
        self.menu.addAction(self.actionSetInterface)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_setPacket.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Генератор пакетов", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Очередь пакетов", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Тип пакета", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Адрес отправителя", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Адрес получателя", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Порт отправителя", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Порт получателя", None, -1))
        self.tableWidget_PacketsQueue.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "EtherType", None, -1))
        self.pushButton_sendAll.setText(QtWidgets.QApplication.translate("MainWindow", "Отправить все пакеты", None, -1))
        self.pushButton_addPacket.setText(QtWidgets.QApplication.translate("MainWindow", "Создать пакет", None, -1))
        self.radioButton_ifDeleteAll.setText(QtWidgets.QApplication.translate("MainWindow", "Удалить все пакеты после отправки", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Настройка пакета", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Указатель на срочные", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "данные", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Флаги", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Смещение данных", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Размер окна", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Зарезервированное поле", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.checkBox_autoDataOffsetTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Данные", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "hex", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "bin", None, -1))
        self.pushButton_saveTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить TCP", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Порт отправки", None, -1))
        self.tableWidget_optionsTCP.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><font face=\"Courier New\"><p>EOL ........ | --- | --- |</p><p>NOP ........ | --- | --- |</p><p>SAckOK ..... | --- | --- |</p><p>AltChkSumOpt | --- | --- |</p><p>Mood ....... | str | --- |</p><p>MSS ........ | int | --- |</p><p>UTO ........ | int | --- |</p><p>WScale ..... | int | --- |</p><p>SAck ....... | int | int |</p><p>Timestamp .. | int | int |</p><p>AltChkSum .. | int | int |</p><p>TFO ........ | int | int |</p></font></body></html>", None, -1))
        self.tableWidget_optionsTCP.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Тип", None, -1))
        self.tableWidget_optionsTCP.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Значение 1", None, -1))
        self.tableWidget_optionsTCP.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Значение 2", None, -1))
        self.pushButton_deleteOptionTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Удалить", None, -1))
        self.pushButton_addOptionTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Добавить", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "ACK", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "hex", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "hex", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Порт назначения", None, -1))
        self.checkBox_autoReservedTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Опции", None, -1))
        self.checkBox_autoChecksumTCP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Контрольная сумма", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "SEQ", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.checkBox_finTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[5] FIN", None, -1))
        self.checkBox_pshTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[2] PSH", None, -1))
        self.checkBox_urgTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[0] URG", None, -1))
        self.checkBox_ackTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[1] ACK", None, -1))
        self.checkBox_rstTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[3] RST", None, -1))
        self.checkBox_synTCP.setText(QtWidgets.QApplication.translate("MainWindow", "[4] SYN", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab_TCP), QtWidgets.QApplication.translate("MainWindow", "TCP", None, -1))
        self.label_86.setText(QtWidgets.QApplication.translate("MainWindow", "Данные", None, -1))
        self.checkBox_autoLengthUDP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_87.setText(QtWidgets.QApplication.translate("MainWindow", "Порт отправки", None, -1))
        self.label_91.setText(QtWidgets.QApplication.translate("MainWindow", "Порт назначения", None, -1))
        self.checkBox_autoChecksumUDP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_56.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_58.setText(QtWidgets.QApplication.translate("MainWindow", "hex", None, -1))
        self.label_96.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_97.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.pushButton_saveUDP.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить UDP", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("MainWindow", "Контрольная сумма", None, -1))
        self.label_55.setText(QtWidgets.QApplication.translate("MainWindow", "Длина дейтаграммы", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab_UDP), QtWidgets.QApplication.translate("MainWindow", "UDP", None, -1))
        self.label_67.setText(QtWidgets.QApplication.translate("MainWindow", "Код", None, -1))
        self.pushButton_saveICMP.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить ICMP", None, -1))
        self.label_76.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_60.setText(QtWidgets.QApplication.translate("MainWindow", "Контрольная сумма", None, -1))
        self.label_62.setText(QtWidgets.QApplication.translate("MainWindow", "Данные", None, -1))
        self.label_63.setText(QtWidgets.QApplication.translate("MainWindow", "Тип", None, -1))
        self.label_72.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_75.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.checkBox_autoChecksumICMP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_65.setText(QtWidgets.QApplication.translate("MainWindow", "Идентификатор", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("MainWindow", "ICMP-заголовок", None, -1))
        self.label_53.setText(QtWidgets.QApplication.translate("MainWindow", "Поля эхо-запроса или эхо-ответа", None, -1))
        self.label_61.setText(QtWidgets.QApplication.translate("MainWindow", "Номер последовательности", None, -1))
        self.comboBox_typeICMP.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вручную", None, -1))
        self.comboBox_typeICMP.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Эхо-запрос", None, -1))
        self.comboBox_typeICMP.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Эхо-ответ", None, -1))
        self.label_74.setText(QtWidgets.QApplication.translate("MainWindow", "hex", None, -1))
        self.checkBox_autoCodeICMP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_73.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab_ICMP), QtWidgets.QApplication.translate("MainWindow", "ICMP", None, -1))
        self.comboBox_protocolIP.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вручную", None, -1))
        self.comboBox_protocolIP.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "TCP", None, -1))
        self.comboBox_protocolIP.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "UDP", None, -1))
        self.comboBox_protocolIP.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "ICMP", None, -1))
        self.checkBox_reservedFlagIP.setText(QtWidgets.QApplication.translate("MainWindow", "[0] Зарезервировано", None, -1))
        self.checkBox_dontFragmentFlagIP.setText(QtWidgets.QApplication.translate("MainWindow", "[1] DF", None, -1))
        self.checkBox_moreFragmentsFlagIP.setText(QtWidgets.QApplication.translate("MainWindow", "[2] MF", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "Общая длина", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "IP-адрес отправки", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Длина IP-заголовка", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "Время жизни", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Версия", None, -1))
        self.label_47.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_59.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("MainWindow", "Контрольная сумма", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "IP-адрес назначения", None, -1))
        self.checkBox_autoIDataP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Тип сервиса", None, -1))
        self.checkBox_autoTotalLengthIP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.pushButton_saveIP.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить IP", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Идентификатор", None, -1))
        self.checkBox_autoChecksumIP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "Данные", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Протокол", None, -1))
        self.comboBox_versionIP.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вручную", None, -1))
        self.comboBox_versionIP.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "IPv4", None, -1))
        self.checkBox_autoOffsetIP.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.checkBox_autoIHL.setText(QtWidgets.QApplication.translate("MainWindow", "Авто", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Флаги", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "Опции", None, -1))
        self.label_48.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "dec", None, -1))
        self.label_51.setText(QtWidgets.QApplication.translate("MainWindow", "hex", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "Смещение фрагмента", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "\\xNN\\xNN...", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab_IP), QtWidgets.QApplication.translate("MainWindow", "IP", None, -1))
        self.pushButton_saveEthernet.setText(QtWidgets.QApplication.translate("MainWindow", "Сохранить Ethernet", None, -1))
        self.label_81.setText(QtWidgets.QApplication.translate("MainWindow", "hex", None, -1))
        self.label_68.setText(QtWidgets.QApplication.translate("MainWindow", "EtherType", None, -1))
        self.comboBox_etherType.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вручную", None, -1))
        self.comboBox_etherType.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "IPv4", None, -1))
        self.tabWidget_setPacket.setTabText(self.tabWidget_setPacket.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Ethernet", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Инструменты", None, -1))
        self.actionSetInterface.setText(QtWidgets.QApplication.translate("MainWindow", "Настройка интерфейсов...", None, -1))

